training:
  batch_size: 64
  n_epochs: 500000
  n_iters: 150001
  ngpu: 1
  snapshot_freq: 10000
  algo: 'dsm'
  anneal_power: 2.0

data:
  dataset: "fastMRI"
  image_size: 64
  channels: 8
  logit_transform: false
  random_flip: false

model:
  sigma_begin: 1.0
  sigma_end: 0.01
  num_classes: 10
  batch_norm: false
  ngf: 128
optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.005 
  beta1: 0.9
  amsgrad: false
